#!/bin/sh
#
# tex2l, Peter Csizmadia, Mon May 29 2006     (1998-2006)
#

sed "s/{\\\\'a}/á/g
s/\\\\'a/á/g
s/{\\\\'A}/Á/g
s/\\\\'A/Á/g
s/{\\\\'e}/é/g
s/\\\\'e/é/g
s/{\\\'E}/É/g
s/\\\\'E/É/g
s/{\\\\'\\\\i}/í/g
s/\\\\'\\\\i/í/g
s/{\\\\'\\\\I}/Í/g
s/\\\\'\\\\I/Í/g
s/{\\\\'o}/ó/g
s/\\\\'o/ó/g
s/{\\\\'O}/Ó/g
s/\\\\'O/Ó/g
s/{\\\\'u}/ú/g
s/\\\\'u/ú/g
s/{\\\\'U}/Ú/g
s/\\\\'U/Ú/g
" $* | sed 's/^\\documentclass.*//
s/^\\begin.*//
s/^\\end.*//
s/\\-//g
s/{\\\"o}/ö/g
s/\\"o/ö/g
s/{\\"O}/Ö/g
s/\\"O/Ö/g
s/{\\"u}/ü/g
s/\\"u/ü/g
s/{\\"U}/Ü/g
s/\\"U/Ü/g
s/{\\H o}/õ/g
s/\\H{o}/õ/g
s/\\H o/õ/g
s/\\H{O}/Õ/g
s/{\\H O}/Õ/g
s/\\H O/Õ/g
s/{\\H u}/û/g
s/\\H{u}/û/g
s/\\H u/û/g
s/\\H{U}/Û/g
s/{\\H U}/Û/g
s/\\H U/Û/g'
